POST http://localhost:3002/api/cadastro
Content-Type: application/json


{
    "name" : "Algum serviço",
    "telephone": "23052004",
    "email": "pgasfasjhgf@gmail.com",
    "password": 54244
}


### 

POST http://localhost:3002/api/perguntas


{
    "question" : "THIAGO",
    "option" : [{"alternative1": "ALEX", "alternative2": "GLAUBER", "alternative3": "MARIO", "alternative4": "ROBERIO"}],
    "response" : 1
}

###

POST http://localhost:3002/api/cadastros

###

GET http://localhost:3002/api/cadastros/646263927f22761663aefc93

###

GET http://localhost:3002/api/cadastros

###

DELETE http://localhost:3002/api/cadastros/646263927f22761663aefc93

###

PUT  http://localhost:3002/api/cadastro/646263927f22761663aefc44
Content-Type: application/json


{
    "name" : "TESTE DE ATUALIZAÇÃO!",
    "dateYear": "23052004",
    "email": "pgasfasjhgf@gmail.com",
    "password": 54244
}

###

POST http://localhost:3002/api/login

